version: "3.7"
services:
  mux-client:
    image: golang:alpine
    command:
      - "/bin/sh"
      - "-c"
      - "wget http://mux-server:8080/users/123 && cat 123"
    depends_on:
      - mux-server
  mux-server:
    build:
      dockerfile: ./example/Dockerfile
      context: ../
    ports:
      - "8080:80"
