version: "2.4"
services:
  mux-client:
    image: curlimages/curl:7.84.0
    command: "curl -XGET http://mux-server:8080/users/123"
    depends_on:
      - mux-server
  mux-server:
    build: .
    ports:
      - "8080:8080"
